version: '3.8'

volumes:
  postgres_data_dev:

services:
  postgres:
    image: postgres:12.3-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    env_file:
      - .env

  django: &django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: /start_django_devserver.sh
    depends_on:
      - postgres
      - redis
      - celeryworker
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"

  redis:
    image: library/redis:6-alpine

  celeryworker:
    <<: *django
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start_celeryworker.sh
