# Generated by Django 3.0.7 on 2020-06-04 06:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('iin', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'ИНН должен состоять из 12 цифр')], verbose_name='ИНН')),
                ('birthday', models.DateField(editable=False, verbose_name='дата рождения')),
            ],
            options={
                'verbose_name': 'заёмщик',
                'verbose_name_plural': 'заёмщики',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='минимальная сумма кредита')),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='максимальная сумма кредита')),
                ('min_age', models.PositiveIntegerField(default=21, validators=[django.core.validators.MinValueValidator(18, 'значение не может быть меньше %(limit_value)')], verbose_name='минимальный возраст заёмщика')),
                ('max_age', models.PositiveIntegerField(verbose_name='максимальный возраст заёмщика')),
            ],
            options={
                'verbose_name': 'программа кредитования',
                'verbose_name_plural': 'программы кредитования',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='сумма')),
                ('status', models.CharField(choices=[('pending', 'на рассмотрении'), ('approved', 'одобрено'), ('denied', 'отказано')], default='pending', max_length=50, verbose_name='статус')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='причина отказа')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='lending.Borrower', verbose_name='заёмщик')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='lending.Program', verbose_name='программа')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
            },
        ),
    ]
