# Generated by Django 3.0.7 on 2020-06-04 15:39

import apps.lending.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackIin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('iin', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'ИНН должен состоять из 12 цифр'), apps.lending.models.validate_birthday_in_iin], verbose_name='ИНН')),
            ],
            options={
                'verbose_name': 'заблокированный ИИН',
                'verbose_name_plural': 'заблокированные ИИН',
            },
        ),
        migrations.AlterField(
            model_name='borrower',
            name='iin',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'ИНН должен состоять из 12 цифр'), apps.lending.models.validate_birthday_in_iin], verbose_name='ИНН'),
        ),
    ]
