name: Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        uses: docker/compose-action@v1.0.3
        with:
          compose-file: dev.yml
          run-command: |
            run --rm django python manage.py test
